protocol = "kd-scientific-legato100"
doc = ""
traits = ["is-discrete", "has-position", "uses-uart", "uses-serial", "is-daemon"]
hardware = ["kd-scientific:legato100"]

[links]
source = "https://github.com/yaq-project/yaqd-kd-scientific"
bugtracker = "https://github.com/yaq-project/yaqd-kd-scientific/-/issues"

[installation]
PyPI = "https://pypi.org/project/yaqd-kd-scientific"
conda-forge = "https://anaconda.org/conda-forge/yaqd-kd-scientific"

[config]

[config.identifiers]
default = {"infusing" = 1, "paused" = 0}

[config.baud_rate]
default = 115200

[state]

[messages]

[messages.get_rate]
doc = "Get current rate, in units specified within config."
response = "double"

[messages.set_rate]
doc = "Set current rate, in units specified within config."
request = [{"name"="rate", "type"="double"}]

[messages.rate_units]
doc = "Rate units."
response = "string"

[properties]

[properties.rate]
type = "double"
getter = "get_rate"
setter = "set_rate"
units_getter = "rate_units"
control_kind = "hinted"
record_kind = "metadata"
